importScripts(
  'company-identity.js',
  'cookie-session.js',
  'background.js',
  'status-state-machine.js',
  'followup-core.js',
  'provider-registry.js',
  'application-data.js',
  'followup-strategy.js',
  'session-manager.js',
  'application-matcher.js',
  'change-journal.js',
  'followup-review.js',
  'followup-queue.js',
  'followup-orchestrator.js',
  'followup-background.js',
  'followup-actions.js'
);
