const fs=require('fs'),vm=require('vm'),path=require('path'),assert=require('assert');
const fieldNames=['公司','岗位名称','工作地点','投递时间','当前状态','招聘平台','岗位链接','最近更新时间','下一步行动','面试时间','优先级','备注','唯一记录ID','原始状态','自动跟进','最后检查时间','状态更新时间','检查状态','登录状态','最近错误','招聘系统','检查方式'];
const page='https://demo.jobs.feishu.cn/123/position/application'; const api='https://demo.jobs.feishu.cn/api/candidate/application/list';
const rows=[{record_id:'r1',fields:{'公司':'示例科技','岗位名称':'大模型算法工程师','当前状态':'筛选中','招聘平台':'demo.jobs.feishu.cn','岗位链接':page,'唯一记录ID':'u1'}}];
const store={settings:{appId:'a',appSecret:'s',appToken:'app',tableId:'tbl',baseUrl:'',followUpEnabled:true,followUpIntervalHours:6,followUpMode:'open_tabs',followUpMaxSitesPerRun:12,followUpIncludeTerminal:false,followUpNotify:false,followUpApiFirst:true,followUpStructuredState:true,followUpApiTimeoutSeconds:6,customSites:{},companyAliases:{},trustedAutoSyncHosts:[]}};
const listeners={},alarms=new Map(),updates=[];const event=n=>({addListener(fn){(listeners[n] ||= []).push(fn);}});let scanCalls=0, apiCalls=0, tabsOpen=true;
const chrome={runtime:{onInstalled:event('i'),onStartup:event('s'),onMessage:event('m'),openOptionsPage:async()=>{}},storage:{local:{get:async ks=>Array.isArray(ks)?Object.fromEntries(ks.map(k=>[k,store[k]])):{[ks]:store[ks]},set:async o=>Object.assign(store,o),setAccessLevel:async()=>{}},onChanged:event('c')},alarms:{onAlarm:event('a'),create:async(n,i)=>alarms.set(n,{name:n,periodInMinutes:i.periodInMinutes,scheduledTime:Date.now()+i.delayInMinutes*60000}),get:async n=>alarms.get(n),clear:async n=>alarms.delete(n)},tabs:{query:async()=>tabsOpen?[{id:9,url:page,status:'complete'}]:[],get:async id=>({id,url:page,status:'complete'}),create:async()=>{throw Error('open_tabs must not create')},remove:async()=>{},sendMessage:async(id,msg)=>{if(msg.type==='COLLECT_STRATEGY_PROBE')return{ok:true,page:{url:page},resources:[{url:api,initiatorType:'fetch'}],jsonSnapshots:[]};if(msg.type==='SCAN_PAGE'){scanCalls++;return{ok:true,detected:true,records:[]}};if(msg.type==='ENHANCE_RECORDS')return{ok:true,records:msg.records||[]};if(msg.type==='PROBE_PAGE')return{ok:true};return{ok:false}}},scripting:{executeScript:async()=>[]},notifications:{create:async()=>''}};
function resp(j,status=200){const body=JSON.stringify(j);return{ok:status>=200&&status<300,status,statusText:'OK',headers:{get:k=>k==='content-type'?'application/json':null},json:async()=>j,text:async()=>body};}
async function fetchMock(url,opt={}){url=String(url);if(url===api){apiCalls++;return resp({data:{applications:[{positionName:'大模型算法工程师',applicationStatus:'面试中',applyTime:'2026-08-10'}]}})}if(url.includes('/auth/'))return resp({code:0,tenant_access_token:'t',expire:7200});if(url.includes('/fields?'))return resp({code:0,data:{items:fieldNames.map((n,i)=>({field_name:n,field_id:'f'+i,type:1,is_primary:i===0})),has_more:false}});if(url.includes('/records?'))return resp({code:0,data:{items:rows,has_more:false}});if(url.includes('/batch_update')){updates.push(JSON.parse(opt.body));return resp({code:0,data:{records:[]}})}throw Error('unexpected fetch '+url)}
const ctx={console,chrome,fetch:fetchMock,URL,URLSearchParams,AbortController,setTimeout,clearTimeout,globalThis:null};ctx.globalThis=ctx;vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(__dirname,'..','background.js'),'utf8'),ctx);ctx.OfferTrackFollowUpCore=require('../followup-core.js');ctx.OfferTrackProviderRegistry=require('../provider-registry.js');ctx.OfferTrackApplicationData=require('../application-data.js');ctx.OfferTrackFollowUpStrategy=require('../followup-strategy.js');vm.runInContext(fs.readFileSync(path.join(__dirname,'..','followup-background.js'),'utf8'),ctx);
(async()=>{let r=await ctx.OfferTrackFollowUp._execute('manual');assert.strictEqual(r.changed,1);assert.strictEqual(scanCalls,0);assert.strictEqual(r.strategyStats.api_get,1);assert(store.followUpApiHints?.['demo.jobs.feishu.cn'],'successful GET should be cached');let patched=updates.flatMap(x=>x.records).find(x=>x.record_id==='r1');assert.strictEqual(patched.fields['检查方式'],'API GET');tabsOpen=false;updates.length=0;r=await ctx.OfferTrackFollowUp._execute('manual');assert.strictEqual(r.strategyStats.api_get,1,'cached API should work without open tab');assert(apiCalls>=2);console.log('OfferTrack API-first + cached API E2E: PASS');})();
