const fs=require('fs'),vm=require('vm'),path=require('path'),assert=require('assert');
const fieldNames=['公司','岗位名称','工作地点','投递时间','当前状态','招聘平台','岗位链接','最近更新时间','唯一记录ID','原始状态','自动跟进','最后检查时间','状态更新时间','检查状态','登录状态'];
const rows=[{record_id:'xp-r',fields:{'公司':'小鹏汽车','岗位名称':'【27届校招】基座模型/多模态模型算法工程师','当前状态':'筛选中','招聘平台':'xiaopeng.jobs.feishu.cn','岗位链接':'https://xiaopeng.jobs.feishu.cn/398875/position/application','唯一记录ID':'xp-uid'}}];
const store={settings:{appId:'a',appSecret:'s',appToken:'app',tableId:'tbl',baseUrl:'',followUpEnabled:true,followUpIntervalHours:6,followUpMode:'background_tabs',followUpMaxSitesPerRun:12,followUpIncludeTerminal:false,followUpNotify:false,followUpTabTimeoutSeconds:2,customSites:{},companyAliases:{},trustedAutoSyncHosts:[]}};
const listeners={},alarms=new Map(),created=[],removed=[],updates=[]; const event=n=>({addListener(fn){(listeners[n] ||= []).push(fn);}});
const chrome={runtime:{onInstalled:event('i'),onStartup:event('s'),onMessage:event('m'),openOptionsPage:async()=>{}},storage:{local:{get:async ks=>Array.isArray(ks)?Object.fromEntries(ks.map(k=>[k,store[k]])):{[ks]:store[ks]},set:async o=>Object.assign(store,o),setAccessLevel:async()=>{}},onChanged:event('c')},alarms:{onAlarm:event('a'),create:async(n,i)=>alarms.set(n,{name:n,periodInMinutes:i.periodInMinutes,scheduledTime:Date.now()+i.delayInMinutes*60000}),get:async n=>alarms.get(n),clear:async n=>alarms.delete(n)},tabs:{query:async()=>[],create:async o=>{created.push(o);return{id:88,url:o.url,status:'complete'}},get:async id=>({id,url:'https://xiaopeng.jobs.feishu.cn/398875/position/application',status:'complete'}),remove:async id=>removed.push(id),sendMessage:async(id,msg)=>msg.type==='SCAN_PAGE'?{ok:true,detected:true,page:{host:'xiaopeng.jobs.feishu.cn'},records:[{company:'小鹏汽车',position:'【27届校招】基座模型/多模态模型算法工程师',status:'笔试/测评',rawStatus:'待测评',platform:'xiaopeng.jobs.feishu.cn',url:'https://xiaopeng.jobs.feishu.cn/398875/position/application',uid:'new'}]}:{ok:true,records:msg.records||[]}},notifications:{create:async()=>''}};
const response=j=>({ok:true,status:200,statusText:'OK',json:async()=>j}); async function fetchMock(url,opt={}){url=String(url);if(url.includes('/auth/'))return response({code:0,tenant_access_token:'t',expire:7200});if(url.includes('/fields?'))return response({code:0,data:{items:fieldNames.map((n,i)=>({field_name:n,field_id:'f'+i,type:1,is_primary:i===0})),has_more:false}});if(url.includes('/records?'))return response({code:0,data:{items:rows,has_more:false}});if(url.includes('/batch_update')){updates.push(JSON.parse(opt.body));return response({code:0,data:{records:[]}})}throw Error(url)}
const ctx={console,chrome,fetch:fetchMock,URL,URLSearchParams,setTimeout,clearTimeout,globalThis:null};ctx.globalThis=ctx;ctx.importScripts=()=>{};vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(__dirname,'..','background.js'),'utf8'),ctx);ctx.OfferTrackFollowUpCore=require(path.join(__dirname,'..','followup-core.js'));ctx.OfferTrackProviderRegistry=require(path.join(__dirname,'..','provider-registry.js'));vm.runInContext(fs.readFileSync(path.join(__dirname,'..','followup-background.js'),'utf8'),ctx);
(async()=>{const r=await ctx.OfferTrackFollowUp._execute('manual');assert.strictEqual(created.length,1);assert.strictEqual(created[0].active,false);assert.deepStrictEqual(removed,[88]);assert.strictEqual(r.changed,1);const patched=updates.flatMap(x=>x.records).find(x=>x.record_id==='xp-r');assert(patched && patched.fields['当前状态']==='笔试/测评');assert.ok(!Object.prototype.hasOwnProperty.call(patched.fields,'招聘系统'),'provider diagnostics must stay out of Feishu');assert(r.providers.some(x=>x.id==='feishu_jobs'),'provider detection must remain observable internally');console.log('OfferTrack background-tab experimental mode: PASS');})();
