const fs=require('fs'), path=require('path'), assert=require('assert');
const root=path.join(__dirname,'..');
const manifest=JSON.parse(fs.readFileSync(path.join(root,'manifest.json'),'utf8'));
const scripts=manifest.content_scripts.flatMap(x=>x.js||[]);
assert(!scripts.includes('content-ui.js'));
assert(!fs.existsSync(path.join(root,'content-ui.js')));
const content=fs.readFileSync(path.join(root,'content.js'),'utf8');
assert(!/characterData\s*:\s*true/.test(content));
assert(/AUTO_SCAN_MIN_GAP\s*=\s*4000/.test(content));
assert(/isOfferTrackNode/.test(content));
const semantic=fs.readFileSync(path.join(root,'semantic.js'),'utf8');
assert(!/chrome\.runtime\.sendMessage\s*=/.test(semantic));
assert(!/setInterval\s*\(/.test(semantic));
assert(/MAX_SCRIPT_CHARS\s*=\s*900_000/.test(semantic));
const probe=fs.readFileSync(path.join(root,'strategy-probe.js'),'utf8');
assert(/budget=450_000/.test(probe));
const bg=fs.readFileSync(path.join(root,'followup-background.js'),'utf8');
assert(/nodes\+\+ > 1400/.test(bg));
console.log('OfferTrack v2.2.1 performance safety guards: PASS');
