const fs = require('fs');
const path = require('path');
const assert = require('assert');
const source = fs.readFileSync(path.join(__dirname, '..', 'service-worker.js'), 'utf8');
const state = source.indexOf("status-state-machine.js");
const core = source.indexOf("followup-core.js");
const appData = source.indexOf("application-data.js");
const provider = source.indexOf("provider-registry.js");
const background = source.indexOf("followup-background.js");
assert(state >= 0 && core >= 0 && appData >= 0, 'status consumers must be loaded');
assert(state < core && state < appData, 'Status State Machine must load before normalization consumers');
assert(provider >= 0, 'service worker must load provider-registry.js');
assert(background >= 0, 'service worker must load followup-background.js');
assert(provider < background, 'provider registry must load before follow-up background');
console.log('OfferTrack service worker import order: PASS');
