const fs=require('fs'),vm=require('vm'),path=require('path'),assert=require('assert');
const fields=['公司','岗位名称','工作地点','投递时间','当前状态','招聘平台','岗位链接','最近更新时间','唯一记录ID','原始状态','自动跟进','最后检查时间','状态更新时间','检查状态','登录状态'];
const page='https://demo.jobs.feishu.cn/1/position/application'; const api='https://demo.jobs.feishu.cn/api/application/status';
const rows=[{record_id:'x',fields:{'公司':'示例','岗位名称':'算法工程师','当前状态':'筛选中','招聘平台':'demo.jobs.feishu.cn','岗位链接':page}}];
const store={settings:{appId:'a',appSecret:'s',appToken:'app',tableId:'tbl',followUpEnabled:true,followUpIntervalHours:6,followUpMode:'open_tabs',followUpMaxSitesPerRun:12,followUpApiFirst:true,followUpStructuredState:true,followUpNotify:false,customSites:{},companyAliases:{},trustedAutoSyncHosts:[]}};
const listeners={},alarms=new Map(),updates=[];const event=n=>({addListener(fn){(listeners[n] ||= []).push(fn);}});let scanCalls=0;
const chrome={runtime:{onInstalled:event('i'),onStartup:event('s'),onMessage:event('m')},storage:{local:{get:async ks=>Array.isArray(ks)?Object.fromEntries(ks.map(k=>[k,store[k]])):{[ks]:store[ks]},set:async o=>Object.assign(store,o),setAccessLevel:async()=>{}},onChanged:event('c')},alarms:{onAlarm:event('a'),create:async(n,i)=>alarms.set(n,{name:n,periodInMinutes:i.periodInMinutes,scheduledTime:Date.now()+i.delayInMinutes*60000}),get:async n=>alarms.get(n),clear:async n=>alarms.delete(n)},tabs:{query:async()=>[{id:1,url:page,status:'complete'}],get:async id=>({id,url:page,status:'complete'}),sendMessage:async(id,msg)=>{if(msg.type==='COLLECT_STRATEGY_PROBE')return{ok:true,page:{url:page},resources:[{url:api}],jsonSnapshots:[{data:{menu:{title:'跟进应聘进度，查询暂存投递记录',status:'处理中'}}}]};if(msg.type==='SCAN_PAGE'){scanCalls++;return{ok:true,detected:true,page:{url:page},records:[{company:'示例',position:'算法工程师',status:'面试中',rawStatus:'面试中',platform:'demo.jobs.feishu.cn',url:page}]}};if(msg.type==='ENHANCE_RECORDS')return{ok:true,records:msg.records};if(msg.type==='PROBE_PAGE')return{ok:true};return{ok:false}},create:async()=>{throw Error('no')},remove:async()=>{}},scripting:{executeScript:async()=>[]},notifications:{create:async()=>''}};
function resp(j,status=200){const body=JSON.stringify(j);return{ok:status>=200&&status<300,status,statusText:'OK',headers:{get:k=>k==='content-type'?'application/json':null},json:async()=>j,text:async()=>body};}
async function fetchMock(url,opt={}){url=String(url);if(url===api)return resp({data:{status:'ok',message:'not application data'}});if(url.includes('/auth/'))return resp({code:0,tenant_access_token:'t',expire:7200});if(url.includes('/fields?'))return resp({code:0,data:{items:fields.map((n,i)=>({field_name:n,field_id:'f'+i,type:1,is_primary:i===0})),has_more:false}});if(url.includes('/records?'))return resp({code:0,data:{items:rows,has_more:false}});if(url.includes('/batch_update')){updates.push(JSON.parse(opt.body));return resp({code:0,data:{records:[]}})}throw Error(url)}
const ctx={console,chrome,fetch:fetchMock,URL,URLSearchParams,AbortController,setTimeout,clearTimeout,globalThis:null};ctx.globalThis=ctx;vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(__dirname,'..','background.js'),'utf8'),ctx);ctx.OfferTrackFollowUpCore=require('../followup-core.js');ctx.OfferTrackProviderRegistry=require('../provider-registry.js');ctx.OfferTrackApplicationData=require('../application-data.js');ctx.OfferTrackFollowUpStrategy=require('../followup-strategy.js');vm.runInContext(fs.readFileSync(path.join(__dirname,'..','followup-background.js'),'utf8'),ctx);
(async()=>{const r=await ctx.OfferTrackFollowUp._execute('manual');assert.strictEqual(scanCalls,1);assert.strictEqual(r.strategyStats.page_scan,1);assert.strictEqual(r.changed,1);const patch=updates.flatMap(x=>x.records).find(x=>x.record_id==='x');assert.ok(!Object.prototype.hasOwnProperty.call(patch.fields,'检查方式'),'diagnostic strategy must stay out of Feishu');assert.strictEqual(patch.fields['当前状态'],'面试中');console.log('OfferTrack API/State failure -> Page Scan fallback: PASS');})();
