const fs=require('fs'),vm=require('vm'),path=require('path'),assert=require('assert');
const {fieldNames,installPreBackground,installFollowUpDeps}=require('./runtime-test-helpers.js');
const page='https://demo.jobs.feishu.cn/123/position/application';
const rows=[{record_id:'r1',fields:{'公司':'示例科技','岗位名称':'大模型算法工程师','当前状态':'筛选中','招聘平台':'demo.jobs.feishu.cn','岗位链接':page,'唯一记录ID':'u1'}}];
const store={settings:{appId:'a',appToken:'app',tableId:'tbl',baseUrl:'',followUpEnabled:true,followUpIntervalHours:6,followUpMode:'open_tabs',followUpMaxSitesPerRun:12,followUpIncludeTerminal:false,followUpNotify:false,followUpApiFirst:true,followUpStructuredState:true,customSites:{},companyAliases:{},trustedAutoSyncHosts:[]}};
const listeners={},alarms=new Map(),updates=[]; const event=n=>({addListener(fn){(listeners[n] ||= []).push(fn);}}); let scanCalls=0;
const chrome={runtime:{onInstalled:event('i'),onStartup:event('s'),onMessage:event('m'),openOptionsPage:async()=>{}},storage:{local:{get:async ks=>Array.isArray(ks)?Object.fromEntries(ks.map(k=>[k,store[k]])):{[ks]:store[ks]},set:async o=>Object.assign(store,o),setAccessLevel:async()=>{}},onChanged:event('c')},alarms:{onAlarm:event('a'),create:async(n,i)=>alarms.set(n,{name:n,periodInMinutes:i.periodInMinutes,scheduledTime:Date.now()+i.delayInMinutes*60000}),get:async n=>alarms.get(n),clear:async n=>alarms.delete(n)},tabs:{query:async()=>[{id:7,url:page,status:'complete'}],get:async id=>({id,url:page,status:'complete'}),create:async()=>{throw Error('must not create')},remove:async()=>{},sendMessage:async(id,msg)=>{if(msg.type==='COLLECT_STRATEGY_PROBE')return{ok:true,page:{url:page,title:'招聘'},resources:[],jsonSnapshots:[{source:'__NEXT_DATA__',data:{props:{applications:[{positionName:'大模型算法工程师',applicationStatus:'待测评',cityName:'深圳',applyTime:'2026-08-10'}]}}}]};if(msg.type==='SCAN_PAGE'){scanCalls++;return{ok:true,detected:true,records:[]}};if(msg.type==='ENHANCE_RECORDS')return{ok:true,records:msg.records||[]};if(msg.type==='PROBE_PAGE')return{ok:true,loginRequired:false};return{ok:false}}},scripting:{executeScript:async()=>[]},notifications:{create:async()=>''}};
function resp(j,url=''){const body=JSON.stringify(j);return{ok:true,status:200,statusText:'OK',url,headers:{get:()=> 'application/json'},json:async()=>j,text:async()=>body};}
async function fetchMock(url,opt={}){url=String(url);if(url.includes('/auth/'))return resp({code:0,tenant_access_token:'t',expire:7200},url);if(url.includes('/fields?'))return resp({code:0,data:{items:fieldNames.map((n,i)=>({field_name:n,field_id:'f'+i,type:1,is_primary:i===0})),has_more:false}},url);if(url.includes('/records?'))return resp({code:0,data:{items:rows,has_more:false}},url);if(url.includes('/batch_update')){updates.push(JSON.parse(opt.body));return resp({code:0,data:{records:[]}},url)}throw Error('unexpected fetch '+url)}
const ctx={console,chrome,fetch:fetchMock,URL,URLSearchParams,AbortController,setTimeout,clearTimeout,globalThis:null};ctx.globalThis=ctx;installPreBackground(ctx);vm.createContext(ctx);vm.runInContext(fs.readFileSync(path.join(__dirname,'..','background.js'),'utf8'),ctx);installFollowUpDeps(ctx);vm.runInContext(fs.readFileSync(path.join(__dirname,'..','followup-background.js'),'utf8'),ctx);
(async()=>{const r=await ctx.OfferTrackFollowUp._execute('manual');assert.strictEqual(r.changed,1);assert.strictEqual(scanCalls,0,'structured state should avoid page scan');assert.strictEqual(r.strategyStats.structured_state,1);const patched=updates.flatMap(x=>x.records).find(x=>x.record_id==='r1');assert.strictEqual(patched.fields['当前状态'],'笔试/测评');assert.ok(!Object.prototype.hasOwnProperty.call(patched.fields,'检查方式'),'diagnostic strategy must stay out of Feishu');assert.ok(!Object.prototype.hasOwnProperty.call(patched.fields,'检查状态'),'operational diagnostics must stay out of Feishu');console.log('OfferTrack structured-state strategy E2E: PASS');})();
