const fs=require('fs'), path=require('path'), assert=require('assert');
const root=path.join(__dirname,'..');
const manifest=JSON.parse(fs.readFileSync(path.join(root,'manifest.json'),'utf8'));
assert(/^2\.3\./.test(manifest.version));
assert(!manifest.permissions.includes('cookies'));
const sw=fs.readFileSync(path.join(root,'service-worker.js'),'utf8');
assert(sw.indexOf('session-manager.js') >= 0 && sw.indexOf('session-manager.js') < sw.indexOf('followup-background.js'));
const sm=fs.readFileSync(path.join(root,'session-manager.js'),'utf8');
assert(/MAX_ENTRIES\s*=\s*120/.test(sm));
assert(/MAX_AGE_MS\s*=\s*90/.test(sm));
assert(!/cookie/i.test(sm));
const content=fs.readFileSync(path.join(root,'content.js'),'utf8');
assert(/AUTO_SCAN_MIN_GAP\s*=\s*4000/.test(content));
const semantic=fs.readFileSync(path.join(root,'semantic.js'),'utf8');
assert(!/setInterval\s*\(/.test(semantic));
console.log('v2.3 privacy/performance safety guards: PASS');